### ISSUE TITLE
Error with multiple api key

### ISSUE THREAD

**Issue by saileshkush95** [jackPanyj/vscode_tinypng#3]
I'm trying to add multiple api key like below. But I'm getting authentication key error.
tinypng.apiKeys: ['first-api-key', 'second-api-key', 'third-api-key']

Am I missing somethings?

**Comment by jackPanyj** [comment]
if you set one, is it report errors?

**Comment by saileshkush95** [comment]
Nop, it is working fine with one api key.

**Comment by jackPanyj** [comment]
I don't find some problem. you don't miss anything.
this is my settings:
![image](https://user-images.githubusercontent.com/12585605/65487288-26b24e80-ded9-11e9-9e8e-b59b9126e44b.png)
I compressed 604 images.
![image](https://user-images.githubusercontent.com/12585605/65487246-100bf780-ded9-11e9-945c-10eddccf1c8a.png)

you can see the src/extension.ts file to debug
